services:
  system-monitor:
    build: .
    container_name: cpp-system-monitor
    restart: unless-stopped

    # ports:
    #   - "9906:9906"

    # # 给容器更多权限来访问系统信息
    # privileged: true

    # # 挂载主机的proc文件系统（可选，用于更准确的系统信息）
    # volumes:
    #   - /proc:/proc:ro

    # # 添加网络模式和安全选项
    # # (尽量不要这样，只是读取系统信息（如 cpuinfo、meminfo）可以 不挂载 /proc，容器默认会使用自己的 /proc（不影响读取大多数信息）)
    # network_mode: host
    # security_opt:
    #   - seccomp:unconfined
