FROM python:3.10-slim
COPY requirements.txt ./
RUN pip install --default-timeout=300000 --trusted-host mirrors.aliyun.com -i https://mirrors.aliyun.com/pypi/simple/ -r requirements.txt && rm -f /requirements.txt