################################
# 基础配置
################################

允许所有机器访问
bind 0.0.0.0

# 监听端口
port 6379

# 关闭保护模式
protected-mode no

# 数据目录（docker-compose 里挂载到宿主机）
dir /data

# 开启密码访问
requirepass AfV(!!=L90

################################
# 日志配置
################################

# 日志级别：debug | verbose | notice | warning
loglevel debug

# 日志文件，空字符串表示输出到 stdout
logfile ""

# 开启键过期事件通知（调试时能看到 key 过期）
notify-keyspace-events Ex

################################
# 持久化配置
################################

# 开启 AOF 持久化（调试时能保证数据不丢）
appendonly yes
appendfsync everysec

################################
# 慢查询日志配置
################################

# 记录所有命令（单位：微秒，0 表示所有命令都会被记录）
slowlog-log-slower-than 0

# 最多保留多少条慢查询日志
slowlog-max-len 1024